# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tender_number', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, default='')),
                ('end_date', models.DateTimeField(blank=True, default='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
