# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytenders', '0002_auto_20170821_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_number',
            field=models.CharField(max_length=40),
        ),
    ]
