# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytenders', '0003_auto_20170821_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ('start_date',)},
        ),
        migrations.RemoveField(
            model_name='tender',
            name='created',
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_number',
            field=models.TextField(),
        ),
    ]
